# Provisioning automático de la fuente de datos Prometheus en Grafana.
apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090     # nombre del servicio en docker-compose
    isDefault: true
    editable: true
